# Generated by Django 4.2.9 on 2024-02-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='delete_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='update_at',
            field=models.DateField(),
        ),
    ]
