# Generated by Django 4.2.9 on 2024-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_alter_reimbursement_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='delete_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
